language: node_js
sudo: true

dist: trusty

node_js:
  - "8"
  - "6"

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    - YARN_VER=1.3.2

before_install:
  # Install latest yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VER
  - export PATH="$HOME/.yarn/bin:$PATH"

  # Install @angular/cli
  - npm install -g @angular/cli

  # install the dependencies and build the necessary files
  - cd test-app && yarn install && yarn build:browser && yarn build:server

script:
  # run the test script in the directory
  - cd test-app && yarn test


